Repository AY1920S1-CS2103T-T10-1/main, pull requests merged in 2019-11, with the labels that each got.

#214 Add ListTask Command
  docs/UserGuide.adoc
  src/main/java/seedu/jarvis/logic/commands/planner/AddTaskCommand.java
  src/main/java/seedu/jarvis/logic/commands/planner/ListTaskCommand.java
  src/main/java/seedu/jarvis/logic/parser/JarvisParser.java
  src/test/java/seedu/jarvis/logic/commands/CommandTestUtil.java
  src/test/java/seedu/jarvis/logic/commands/planner/ListTaskCommandTest.java
Labels: feature.Planner, priority.High, type.Task

#309 Update user guide
  docs/UserGuide.adoc
Labels: feature.Planner, type.Bug, type.Task

#315 Update UG
  docs/UserGuide.adoc
  src/main/java/seedu/jarvis/model/finance/FinanceTracker.java
  src/main/java/seedu/jarvis/ui/finance/FinanceListView.java
  src/main/resources/view/FinanceListView.fxml
Labels: feature.Finance, priority.High, type.Bug

#321 Fix bugs
  docs/UserGuide.adoc
  src/main/java/seedu/jarvis/commons/core/Messages.java
  src/main/java/seedu/jarvis/commons/util/StringUtil.java
  src/main/java/seedu/jarvis/logic/commands/planner/AddTaskCommand.java
  src/main/java/seedu/jarvis/logic/parser/ParserUtil.java
  src/main/java/seedu/jarvis/logic/parser/planner/AddTaskCommandParser.java
  src/main/java/seedu/jarvis/model/planner/tasks/Task.java
  src/main/java/seedu/jarvis/ui/planner/TaskCard.java
  src/test/java/seedu/jarvis/commons/util/StringUtilTest.java
  src/test/java/seedu/jarvis/logic/parser/ParserUtilTest.java
  src/test/java/seedu/jarvis/logic/parser/planner/AddTaskCommandParserTest.java
  src/test/java/seedu/jarvis/model/planner/TaskDesContainsKeywordsPredicateTest.java
Labels: feature.Planner, priority.High, type.Bug, type.Task

#324 Fix date
  src/main/java/seedu/jarvis/logic/parser/ParserUtil.java
Labels: feature.Planner, priority.High, type.Bug

#325 Multiple prefixes
  src/main/java/seedu/jarvis/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/jarvis/logic/parser/ParserUtil.java
  src/main/java/seedu/jarvis/logic/parser/planner/AddTaskCommandParser.java
Labels: feature.Planner, type.Bug, type.Task

#332 Add JsonAdaptedClearCourseCommand
  docs/tutorials/AddRemark.adoc
  docs/tutorials/RemovingFields.adoc
  docs/tutorials/TracingCode.adoc
  src/main/java/seedu/jarvis/logic/commands/course/ClearCourseCommand.java
  src/main/java/seedu/jarvis/model/ModelManager.java
  src/main/java/seedu/jarvis/model/userprefs/ReadOnlyUserPrefs.java
  src/main/java/seedu/jarvis/model/userprefs/UserPrefs.java
  src/main/java/seedu/jarvis/model/util/SampleDataUtil.java
  src/main/java/seedu/jarvis/storage/history/commands/JsonAdaptedCommand.java
  src/main/java/seedu/jarvis/storage/history/commands/course/JsonAdaptedAddCourseCommand.java
  src/main/java/seedu/jarvis/storage/history/commands/course/JsonAdaptedClearCourseCommand.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/jarvis/model/ModelManagerTest.java
  src/test/java/seedu/jarvis/model/userprefs/UserPrefsTest.java
  src/test/java/seedu/jarvis/storage/course/JsonAdaptedClearCourseCommandTest.java
  src/test/java/seedu/jarvis/storage/userprefs/JsonUserPrefsStorageTest.java
Labels: feature.Course, feature.UndoRedo, type.Task

#334 Update command format for undo/redo
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/jarvis/logic/commands/CommandDeque.java
  src/main/java/seedu/jarvis/logic/commands/history/RedoCommand.java
  src/main/java/seedu/jarvis/logic/commands/history/UndoCommand.java
  src/main/java/seedu/jarvis/logic/parser/CliSyntax.java
  src/main/java/seedu/jarvis/logic/parser/ParserUtil.java
  src/main/java/seedu/jarvis/logic/parser/history/RedoCommandParser.java
  src/main/java/seedu/jarvis/logic/parser/history/UndoCommandParser.java
  src/test/java/seedu/jarvis/logic/parser/JarvisParserTest.java
  src/test/java/seedu/jarvis/logic/parser/ParserUtilTest.java
  src/test/java/seedu/jarvis/logic/parser/history/RedoCommandParserTest.java
  src/test/java/seedu/jarvis/logic/parser/history/UndoCommandParserTest.java
Labels: feature.UndoRedo, priority.Low

#337 Add colours to labels in Planner UI
  src/main/java/seedu/jarvis/ui/MainWindow.java
  src/main/java/seedu/jarvis/ui/planner/PlannerView.java
  src/main/java/seedu/jarvis/ui/planner/TaskCard.java
  src/main/resources/view/PlannerView.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/cssfiles/CustomExtensions.css
  src/main/resources/view/cssfiles/CustomLightTheme.css
  src/main/resources/view/cssfiles/Extensions.css
Labels: feature.Planner, feature.UI, priority.Medium

#345 Updated data fields in JsonSerializableFinanceTracker
  src/main/java/seedu/jarvis/storage/finance/JsonSerializableFinanceTracker.java
Labels: feature.Finance, priority.High, type.Bug

#344 Edit FinanceTracker Ui
  docs/UserGuide.adoc
  docs/diagrams/feature cca-tracker/IncreaseCcaProgressActivityDiagram.puml
  docs/diagrams/feature course-planner/CheckActivityDiagram.puml
  docs/diagrams/feature finance-tracker/EditInstallment.puml
  docs/diagrams/feature undo-redo/CommandClassDiagram.puml
  docs/diagrams/feature undo-redo/HistoryManagerModelClassDiagram.puml
  docs/diagrams/feature undo-redo/InverseCommandActivityDiagram.puml
  docs/diagrams/feature undo-redo/RedoCommandActivityDiagram.puml
  docs/diagrams/feature undo-redo/UndoCommandActivityDiagram.puml
  docs/diagrams/feature undo-redo/UndoSequenceDiagramOld.puml
  src/main/java/seedu/jarvis/MainApp.java
  src/main/java/seedu/jarvis/commons/core/Messages.java
  src/main/java/seedu/jarvis/logic/commands/finance/FindPurchaseCommand.java
  src/main/java/seedu/jarvis/logic/commands/finance/ListFinancesCommand.java
  src/main/java/seedu/jarvis/logic/commands/finance/SetInstallmentCommand.java
  src/main/java/seedu/jarvis/logic/commands/finance/SetMonthlyLimitCommand.java
  src/main/java/seedu/jarvis/model/ModelManager.java
  src/main/java/seedu/jarvis/model/finance/FinanceTracker.java
  src/main/java/seedu/jarvis/model/finance/FinanceTrackerModel.java
  src/main/java/seedu/jarvis/model/finance/PurchaseList.java
  src/main/java/seedu/jarvis/model/util/SampleDataUtil.java
  src/main/java/seedu/jarvis/storage/finance/JsonSerializableFinanceTracker.java
  src/main/java/seedu/jarvis/ui/UiManager.java
  src/main/java/seedu/jarvis/ui/finance/FinanceListView.java
  src/main/java/seedu/jarvis/ui/finance/InstallmentCard.java
  src/main/java/seedu/jarvis/ui/finance/PurchaseCard.java
  src/main/resources/view/FinanceListView.fxml
  src/main/resources/view/InstallmentListCard.fxml
  src/main/resources/view/PurchaseListCard.fxml
  src/main/resources/view/cssfiles/FinanceTheme.css
  src/test/java/seedu/jarvis/logic/commands/finance/FindPurchaseCommandTest.java
  src/test/java/seedu/jarvis/logic/commands/finance/SetInstallmentCommandTest.java
  src/test/java/seedu/jarvis/model/finance/FinanceTrackerTest.java
  src/test/java/seedu/jarvis/model/finance/PurchaseListTest.java
  src/test/java/seedu/jarvis/storage/StorageManagerTest.java
  src/test/java/seedu/jarvis/testutil/ModelStub.java
  src/test/java/seedu/jarvis/testutil/finance/TypicalFinances.java
Labels: feature.Finance, feature.UI, priority.High

#347 Fix bug for planner UI
  src/main/java/seedu/jarvis/logic/commands/history/RedoCommand.java
  src/main/java/seedu/jarvis/logic/commands/history/UndoCommand.java
  src/main/java/seedu/jarvis/logic/commands/planner/AddTaskCommand.java
  src/main/java/seedu/jarvis/logic/commands/planner/DeleteTaskCommand.java
  src/main/java/seedu/jarvis/logic/commands/planner/DoneTaskCommand.java
  src/main/java/seedu/jarvis/model/ModelManager.java
  src/main/java/seedu/jarvis/model/planner/Planner.java
  src/main/java/seedu/jarvis/model/planner/PlannerModel.java
  src/main/java/seedu/jarvis/ui/MainWindow.java
  src/test/java/seedu/jarvis/testutil/ModelStub.java
Labels: feature.Planner, feature.UI, type.Bug

#348 Edit finance tracker Ui
  src/main/java/seedu/jarvis/ui/HelpDeskWindow.java
Labels: feature.Finance, feature.UI

#349 Update DG
  docs/DeveloperGuide.adoc
  docs/diagrams/feature course-planner/CheckCommandSequenceDiagram.puml
  docs/diagrams/model-related/ModelCoursePlannerClassDiagram.puml
  docs/images/CheckActivityDiagram.png
  docs/images/CheckCommandSequenceDiagram.png
  docs/images/ModelCoursePlannerClassDiagram.png
  src/main/java/seedu/jarvis/logic/commands/course/ShowCourseHelpCommand.java
Labels: feature.Course, priority.Medium

#351 Branch dg
  docs/DeveloperGuide.adoc
  docs/diagrams/feature undo-redo/CommandClassDiagram.puml
  docs/diagrams/feature undo-redo/HistoryManagerModelClassDiagram.puml
  docs/diagrams/feature undo-redo/RedoSequenceDiagramNew.puml
  docs/images/undoredo/CommandClassDiagram.png
  docs/images/undoredo/HistoryManagerModelClassDiagram.png
  docs/images/undoredo/InverseCommandActivityDiagram.png
  docs/images/undoredo/RedoCommandActivityDiagram.png
  docs/images/undoredo/RedoSequenceDiagramNew.png
  docs/images/undoredo/UndoCommandActivityDiagram.png
  docs/images/undoredo/UndoSequenceDiagramNew.png
Labels: feature.UndoRedo

#353 Update ui
  src/main/java/seedu/jarvis/logic/commands/planner/ListTaskCommand.java
  src/main/java/seedu/jarvis/ui/HelpDeskWindow.java
  src/test/java/seedu/jarvis/logic/commands/planner/ListTaskCommandTest.java
Labels: feature.UI

#362 Change order of tabs
  docs/diagrams/feature finance-tracker/EditInstallmentActivityDiagram.puml
  docs/diagrams/model-related/ModelCcaTrackerClassDiagram.puml
  src/main/java/seedu/jarvis/model/viewstatus/ViewType.java
  src/main/java/seedu/jarvis/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: feature.UI

#363 Branch command
  docs/DeveloperGuide.adoc
  docs/diagrams/model-related/ModelAddressBookClassDiagram.puml
  docs/diagrams/model-related/ModelCcaTrackerClassDiagram.puml
  docs/diagrams/model-related/ModelClassDiagram.puml
  docs/diagrams/model-related/ModelCoursePlannerClassDiagram.puml
  docs/diagrams/model-related/ModelFinanceTrackerClassDiagram.puml
  docs/diagrams/model-related/ModelHistoryManagerClassDiagram.puml
  docs/diagrams/model-related/ModelInterfaceClassDiagram.puml
  docs/diagrams/model-related/ModelJarvisClassDiagram.puml
  docs/diagrams/model-related/ModelManagerClassDiagram.puml
  docs/diagrams/model-related/ModelPlannerClassDiagram.puml
  docs/diagrams/model-related/ModelUserPrefsClassDiagram.puml
  docs/diagrams/model-related/UpdatedModelClassDiagram.puml
  docs/diagrams/storage/CcaTrackerStorageClassDiagram.puml
  docs/diagrams/storage/CoursePlannerStorageClassDiagram.puml
  docs/diagrams/storage/FinanceTrackerStorageClassDiagram.puml
  docs/diagrams/storage/HistoryManagerStorageClassDiagram.puml
  docs/diagrams/storage/PlannerStorageClassDiagram.puml
  docs/diagrams/storage/UpdatedStorageClassDiagram.puml
  docs/images/model/ModelCcaTrackerClassDiagram.png
  docs/images/model/ModelClassDiagram.png
  docs/images/model/ModelCoursePlannerClassDiagram.png
  docs/images/model/ModelFinanceTrackerClassDiagram.png
  docs/images/model/ModelHistoryManagerClassDiagram.png
  docs/images/model/ModelInterfaceClassDiagram.png
  docs/images/model/ModelManagerClassDiagram.png
  docs/images/model/ModelPlannerClassDiagram.png
  docs/images/model/ModelUserPrefsClassDiagram.png
  docs/images/model/UpdatedModelClassDiagram.png
  docs/images/storage/CcaTrackerStorageClassDiagram.png
  docs/images/storage/CoursePlannerStorageClassDiagram.png
  docs/images/storage/FinanceTrackerStorageClassDiagram.png
  docs/images/storage/HistoryManagerStorageClassDiagram.png
  docs/images/storage/PlannerStorageClassDiagram.png
  docs/images/storage/UpdatedStorageClassDiagram.png
  src/main/java/seedu/jarvis/MainApp.java
  src/main/java/seedu/jarvis/logic/commands/history/ListHistoryCommand.java
  src/main/java/seedu/jarvis/logic/commands/history/RedoCommand.java
  src/main/java/seedu/jarvis/logic/commands/history/UndoCommand.java
  src/main/java/seedu/jarvis/logic/parser/JarvisParser.java
  src/main/java/seedu/jarvis/model/Model.java
  src/main/java/seedu/jarvis/model/history/HistoryManager.java
  src/test/java/seedu/jarvis/logic/commands/history/ListHistoryCommandTest.java
  src/test/java/seedu/jarvis/logic/parser/JarvisParserTest.java
Labels: feature.UndoRedo

#361 Update ug
  docs/UserGuide.adoc
  docs/images/StartUpGUI.png
Labels: priority.High

#365 Update DG, remove "Address" from code
  build.gradle
  docs/DevOps.adoc
  docs/DeveloperGuide.adoc
  docs/Documentation.adoc
  docs/SettingUp.adoc
  docs/Testing.adoc
  docs/images/UiClassDiagram.png
  src/main/java/seedu/jarvis/MainApp.java
  src/main/java/seedu/jarvis/commons/util/CourseUtil.java
  src/main/java/seedu/jarvis/logic/LogicManager.java
  src/main/java/seedu/jarvis/logic/commands/ExitCommand.java
  src/main/java/seedu/jarvis/logic/commands/cca/EditCcaCommand.java
  src/main/java/seedu/jarvis/logic/commands/planner/AddTaskCommand.java
  src/main/java/seedu/jarvis/logic/parser/cca/DeleteCcaCommandParser.java
  src/main/java/seedu/jarvis/model/ModelManager.java
  src/main/java/seedu/jarvis/model/util/SampleDataUtil.java
  src/main/java/seedu/jarvis/storage/StorageManager.java
  src/test/java/seedu/jarvis/logic/commands/cca/DeleteCcaCommandTest.java
  src/test/java/seedu/jarvis/logic/commands/cca/ListCcaCommandTest.java
  src/test/java/seedu/jarvis/logic/commands/finance/EditInstallmentCommandTest.java
  src/test/java/seedu/jarvis/logic/commands/finance/ListFinancesCommandTest.java
Labels: priority.High

#366 Update user guide
  docs/UserGuide.adoc
Labels: feature.UndoRedo

#370 Add pictures to UG
  docs/UserGuide.adoc
  docs/images/StartUpGUI.png
  docs/images/ug/CcaUI.png
  docs/images/ug/CoursePlannerUI.png
  docs/images/ug/ErrorMessage.png
  docs/images/ug/FinanceUI.png
  docs/images/ug/PlannerUI.png
  docs/images/ug/StartUpUI.png
  docs/images/ug/check.png
  docs/images/ug/done-task.png
  docs/images/ug/find-cca.png
  docs/images/ug/find-paid.png
  docs/images/ug/find-task.png
  docs/images/ug/increment-progress.png
  docs/images/ug/list-history.png
  docs/images/ug/lookup.png
  docs/images/ug/pull-task.png
  src/main/java/seedu/jarvis/model/util/SampleDataUtil.java
Labels: priority.High

#371 Update existing diagrams and repackaged diagrams
  docs/diagrams/feature cca-tracker/ModelCcaTrackerClassDiagram.puml
  docs/diagrams/feature course-planner/ModelCoursePlannerClassDiagram.puml
  docs/diagrams/feature finance-tracker/DeletePurchaseSequenceDiagram.puml
  docs/diagrams/feature finance-tracker/EditInstallmentSequenceDiagram.puml
  docs/diagrams/feature finance-tracker/ModelFinanceTrackerClassDiagram.puml
  docs/diagrams/feature planner/ModelPlannerClassDiagram.puml
  docs/diagrams/feature undo-redo/HistoryManagerClassDiagramOld.puml
  docs/diagrams/feature undo-redo/UndoRedoState0.puml
  docs/diagrams/feature undo-redo/UndoRedoState1.puml
  docs/diagrams/feature undo-redo/UndoRedoState2.puml
  docs/diagrams/feature undo-redo/UndoRedoState3.puml
  docs/diagrams/feature undo-redo/UndoRedoState4.puml
  docs/diagrams/feature undo-redo/UndoRedoState5.puml
  docs/diagrams/jarvis model/ModelClassDiagram.puml
  docs/diagrams/jarvis model/ModelInterfaceClassDiagram.puml
  docs/diagrams/jarvis model/ModelJarvisClassDiagram.puml
  docs/diagrams/jarvis model/ModelManagerClassDiagram.puml
  docs/diagrams/jarvis model/ModelUserPrefsClassDiagram.puml
  docs/diagrams/model-related without methods/ModelAddressBookClassDiagram.puml
  docs/diagrams/model-related without methods/ModelClassDiagram.puml
  docs/diagrams/model-related without methods/ModelFinanceTrackerClassDiagram.puml
  docs/diagrams/style2.puml
  src/main/java/seedu/jarvis/commons/core/Messages.java
  src/main/java/seedu/jarvis/logic/commands/finance/FindPurchaseCommand.java
  src/main/java/seedu/jarvis/ui/finance/InstallmentCard.java
  src/main/java/seedu/jarvis/ui/finance/PurchaseCard.java
  src/test/java/seedu/jarvis/logic/commands/CommandTestUtil.java
  src/test/java/seedu/jarvis/logic/commands/finance/EditInstallmentCommandTest.java
  src/test/java/seedu/jarvis/logic/commands/finance/FinanceCommandTestUtil.java
  src/test/java/seedu/jarvis/logic/commands/finance/FindPurchaseCommandTest.java
  src/test/java/seedu/jarvis/logic/parser/finance/EditInstallmentCommandParserTest.java
  src/test/java/seedu/jarvis/logic/parser/finance/SetInstallmentCommandParserTest.java
  src/test/java/seedu/jarvis/logic/parser/finance/SetMonthlyLimitCommandParserTest.java
  src/test/java/seedu/jarvis/logic/parser/finance/SetPaidCommandParserTest.java
Labels: priority.High

#369 Branch dg
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicClassDiagram.puml
  docs/images/CcaTrackerStorageClassDiagram.png
  docs/images/CommandClassDiagram.png
  docs/images/CoursePlannerStorageClassDiagram.png
  docs/images/FinanceTrackerStorageClassDiagram.png
  docs/images/HistoryManagerModelClassDiagram.png
  docs/images/HistoryManagerStorageClassDiagram.png
  docs/images/InverseCommandActivityDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelCcaTrackerClassDiagram.png
  docs/images/ModelCoursePlannerClassDiagram.png
  docs/images/ModelFinanceTrackerClassDiagram.png
  docs/images/ModelHistoryManagerClassDiagram.png
  docs/images/ModelInterfaceClassDiagram.png
  docs/images/ModelPlannerClassDiagram.png
  docs/images/ModelUserPrefsClassDiagram.png
  docs/images/PlannerStorageClassDiagram.png
  docs/images/RedoCommandActivityDiagram.png
  docs/images/RedoSequenceDiagramNew.png
  docs/images/StorageInterfaceClassDiagram.png
  docs/images/UndoCommandActivityDiagram.png
  docs/images/UndoSequenceDiagramNew.png
  docs/images/UpdatedModelClassDiagram.png
  docs/images/UpdatedStorageClassDiagram.png
  docs/images/model/ModelCoursePlannerClassDiagram.png
  docs/images/model/ModelFinanceTrackerClassDiagram.png
  docs/images/storage/ModelJarvisClassDiagram.png
  src/main/java/seedu/jarvis/MainApp.java
  src/main/java/seedu/jarvis/logic/parser/CliSyntax.java
  src/test/java/seedu/jarvis/logic/commands/CommandTestUtil.java
  src/test/java/seedu/jarvis/logic/parser/cca/EditCcaCommandParserTest.java
Labels: priority.High

#372 Add an assertion to Course Planner
  src/main/java/seedu/jarvis/logic/commands/course/ClearCourseCommand.java
  src/main/java/seedu/jarvis/logic/commands/course/LookUpCommand.java
Labels: feature.Course, priority.High

#374 Remove all traces of AddressBook from codebase
  docs/DeveloperGuide.adoc
  docs/SettingUp.adoc
  docs/Testing.adoc
  docs/UserGuide.adoc
  docs/UsingCheckstyle.adoc
  src/main/java/seedu/jarvis/model/finance/InstallmentList.java
  src/main/java/seedu/jarvis/model/finance/exceptions/DuplicateInstallmentException.java
  src/main/java/seedu/jarvis/model/finance/exceptions/DuplicatePurchaseException.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/jarvis/logic/LogicManagerTest.java
  src/test/java/seedu/jarvis/logic/parser/ParserUtilTest.java
Labels: priority.Medium, type.Enhancement

#387 Finalise Course Planner DG and PPP
  docs/DeveloperGuide.adoc
  docs/team/ryanytan.adoc
Labels: feature.Course

#388 Fix all TODOs
  docs/UserGuide.adoc
  src/main/java/seedu/jarvis/MainApp.java
  src/main/java/seedu/jarvis/logic/commands/course/ClearCourseCommand.java
Labels: feature.Course
